import { KumaRegistry } from "@kuma-ui/next-plugin/registry";
import type { Metadata } from "next";

import "./reset.css";
import Header from "@/components/Header";

export const runtime = "edge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body style={{ backgroundColor: "#ECF4D6" }}>
        <KumaRegistry>
          <Header />
          {children}
        </KumaRegistry>
      </body>
    </html>
  );
}
