name: ci-lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: npm install, build, and start
        run: |
          npm install
          npm run build
      - name: install Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
      - name: Start server
        run: npm start &
      - name: run Lighthouse
        run: lhci autorun --collect.url=http://localhost:3000
